// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhgxksnwrpgxxtkibbpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZ3hrc253cnBneHh0a2liYnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTY4NTYsImV4cCI6MjA2MDEzMjg1Nn0.d_BKMHF8sGdR7ZSZD3acx0Ks1R0lYQVE9rTpRWih9Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);